// Static assertions over the generated BYOK artifact — seconds, no browser.
//
// The headless drive (chat → reason → re-run → fork, with a fake key, watching
// every network request) is the behavioural proof. THIS file is the one that
// runs on every change: it re-generates out/byok/ from scratch and then checks
// the properties that make the custody claim true as a matter of construction —
// the import map resolves, nothing key-shaped was written into the artifact, the
// pages have no own-origin data path and no query-string configuration, and the
// model badge says the same honest thing in every mode.
//
// The artifact is a BUNDLE, not a page: index.html is a gallery home (cards, the
// custody contract, the vocabulary — and no key input at all), and each desk is
// its own page. Every custody assertion below therefore runs over EVERY page
// that can hold a key, and the home gets its own set: relative links only, no
// script, no key field, and the honest disabled card for the desk a browser
// cannot run.
//
//   node 08-app-gallery/verify-byok.mjs
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate, serve } from './byok.js';
import { HEADER_LINKS, PROVENANCE_HELP, buildAppPage, buildGalleryPage } from './lib/page.js';
import { trip } from './apps/trip.js';
import { APPS } from './apps/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'out', 'byok');
const MODEL = 'claude-haiku-4-5-20251001';

let failed = 0;
const ok = (cond, label, detail = '') => {
  if (!cond) failed += 1;
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${label}${detail ? ` — ${detail}` : ''}`);
};

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else if (entry.isFile()) yield p;
  }
}

// ═══ generate fresh ═════════════════════════════════════════════════════════
const { imports, pages } = generate({ quiet: true });
const landing = readFileSync(join(outDir, 'index.html'), 'utf8');
// The desk pages, by the file names the home links at. Read back from DISK (not
// from the generator's return) so what is asserted is what a visitor would be
// served — a page the generator built but never wrote would fail here.
const DESKS = ['trip', 'movies'];
const deskPages = DESKS.map((id) => ({ id, file: `${id}.html`, html: readFileSync(join(outDir, `${id}.html`), 'utf8') }));
const bootOf = (h) => h.slice(h.lastIndexOf('<script type="module">'));
// The desk that carries every page-script property; the checks that are about
// the SCRIPT (one shared generator) run once over it and are proven identical
// across desks by the byte-shape check right below.
const boot = bootOf(deskPages[0].html);
console.log('=== BYOK VERIFY ===');

ok(Object.keys(pages).sort().join(' ') === 'index.html movies.html trip.html',
  'the bundle is a home plus one page per desk', Object.keys(pages).join(', '));
for (const d of deskPages) {
  ok(pages[d.file] === d.html, `[${d.id}] the returned page is byte-identical to the file on disk`);
}
// Same generator, same guarantees: everything the boot script promises is
// promised on BOTH desks, so a desk-specific regression cannot hide.
ok(DESKS.every((id) => bootOf(deskPages.find((d) => d.id === id).html).includes('__BYOK_TEST__')),
  'every desk page carries the same generated boot script');

// ═══ (a) the import map resolves ════════════════════════════════════════════
const unresolved = Object.entries(imports)
  .filter(([, target]) => !existsSync(join(outDir, target.replace(/^\.\//, ''))));
ok(unresolved.length === 0, 'every import-map entry points at a generated file',
  `${Object.keys(imports).length} specifiers`);
ok(['node:module', 'node:path', 'node:url'].every((k) => imports[k]?.startsWith('./app/byok/stubs/')),
  'node builtins are satisfied by in-page stubs, not left dangling');

// ═══ (b) nothing key-shaped, no server path, no env read ════════════════════
const REAL_KEY_SHAPE = /sk-ant-[A-Za-z0-9_-]{16,}/;
const offenders = [];
for (const file of walk(outDir)) {
  if (!['.html', '.js', '.json', '.css'].includes(extname(file))) continue;
  const body = readFileSync(file, 'utf8');
  if (REAL_KEY_SHAPE.test(body)) offenders.push(relative(outDir, file));
}
ok(offenders.length === 0, 'no key-shaped literal anywhere in the artifact', offenders.join(', ') || 'clean');

// The owner's own key must be provably absent — the generator never reads it,
// and this proves the artifact never carried it.
const envPath = join(here, '..', '.env');
if (existsSync(envPath)) {
  const ownerKey = (readFileSync(envPath, 'utf8').match(/ANTHROPIC_API_KEY\s*=\s*(\S+)/) ?? [])[1];
  if (ownerKey && ownerKey.length > 20) {
    let leaked = false;
    for (const file of walk(outDir)) {
      if (statSync(file).size > 20e6) continue;
      if (readFileSync(file, 'latin1').includes(ownerKey)) { leaked = true; break; }
    }
    ok(!leaked, "the owner's .env key does not appear anywhere in the artifact");
  } else {
    console.log('SKIP  owner-key check — no usable ANTHROPIC_API_KEY in .env');
  }
} else {
  console.log('SKIP  owner-key check — no .env present');
}

for (const d of deskPages) {
  const b = bootOf(d.html);
  ok(!b.includes('process.env'), `[${d.id}] the page script never reads an environment variable`);
  ok(!/fetch\(\s*['"`]\//.test(b) && !b.includes("'/app/"),
    `[${d.id}] the page has no own-origin data path (no fetch to our server, no /app/ API prefix)`);
  ok(!/location\.search|URLSearchParams|hash\b/.test(b),
    `[${d.id}] no query-string / fragment configuration exists (a crafted link cannot redirect a key-bearing call)`);
  ok(b.includes('__BYOK_TEST__') && b.includes('apiUrlOverride'),
    `[${d.id}] the only API-base override is the in-page test hook, read lazily at provider construction`);
  // The page is React-rendered from an empty <div id="root">, so the only way a
  // form could exist is createElement('form') — assert it never happens.
  ok(!b.includes("e('form'") && !b.includes("createElement('form'")
    && !/<body>[\s\S]*?<div id="root"><\/div>\s*<form/.test(d.html),
    `[${d.id}] the key field is not inside a <form> — no submit default that could put it in a URL`);
}

// ═══ (c) the right provider actually shipped ════════════════════════════════
const providerPath = join(outDir, 'vendor/agentfootprint/dist/esm/adapters/llm/BrowserAnthropicProvider.js');
const provider = existsSync(providerPath) ? readFileSync(providerPath, 'utf8') : '';
ok(provider.includes('anthropic-dangerous-direct-browser-access'),
  'the vendored browser provider carries the documented direct-browser header');
ok(provider.includes('https://api.anthropic.com/v1/messages'),
  'the provider’s API base is the compile-time Anthropic endpoint');
ok(/Browser providers do not read environment variables/.test(provider),
  'the browser provider takes its key ONLY from the caller');

// ═══ key custody, as written ════════════════════════════════════════════════
ok(boot.includes("sessionStorage.setItem"), 'a remembered key is written to sessionStorage');
ok(!boot.includes('localStorage.setItem'), 'nothing is ever written to localStorage');
ok(boot.includes("localStorage.removeItem"), '"Forget my key" clears localStorage too, unconditionally');
ok(/var apiKey = null/.test(boot), 'the key lives in a module-scoped page variable');
ok(boot.includes("keyTail = k.slice(-4)") || boot.includes('slice(-4)'),
  'only the last four characters are ever shown');

// ═══ (d) the custody copy + the three-state badge ═══════════════════════════
// The contract itself — every sentence that makes the custody claim. It is
// asserted on EVERY page of the bundle: the home (where a visitor decides
// whether to bring a key at all) and each desk (where they actually paste it).
// A page that can hold a key without carrying the contract is the failure this
// list exists to catch.
const mustSay = [
  'Your key stays in this tab.',
  'This is a live public demo — it runs entirely in your browser.',
  'this site’s host (GitHub Pages) never receives it',
  'Every Claude call goes straight from your browser to',
  'our demo server never sees your key',
  'there is no server code that',
  'the only requests that carry your key go to',
];
for (const page of [{ id: 'home', html: landing }, ...deskPages]) {
  for (const phrase of mustSay) {
    ok(page.html.includes(phrase), `[${page.id}] custody copy present: “${phrase.slice(0, 46)}…”`);
  }
}
// Where the key is actually armed — the checkbox and the forget button live on
// the desks, and the checkbox now also answers "does it survive the trip back
// to the gallery?", because on this bundle that trip is one click away.
const CHECKBOX = 'Remember my key in this tab (survives reload and the trip back to the gallery; forgotten when the tab closes)';
for (const d of deskPages) {
  ok(d.html.includes(CHECKBOX), `[${d.id}] the remember checkbox says exactly what it does across a same-tab trip`);
  ok(d.html.includes('Forget my key'), `[${d.id}] “Forget my key” is on the desk that holds it`);
  ok(d.html.includes('going back to the gallery clears it'),
    `[${d.id}] an unremembered key is honestly labeled as page-scoped`);
}
// The scope fact — why two desks and not three — lives where the third card is.
ok(landing.includes('the SEC’s servers don’t allow browser calls, so the stock desk runs only in the server demo'),
  '[home] the honest scope line is on the gallery, beside the disabled card');

for (const d of deskPages) {
  ok(d.html.includes("'data-testid': 'model-badge'"), `[${d.id}] the desk renders a model badge`);
  ok(d.html.includes('— direct from your browser · '), `[${d.id}] the badge says the call goes direct from the browser`);
  ok(d.html.includes("'no key yet'"), `[${d.id}] the badge has an honest no-key state`);
  ok(d.html.includes(MODEL), `[${d.id}] the badge names the real model id (${MODEL})`);
  ok(!d.html.includes('scripted mock'), `[${d.id}] never claims a mock — the desk is live-only by definition`);
}

// ═══ (e) THE GALLERY HOME ═══════════════════════════════════════════════════
// index.html is a landing, not a desk: it teaches and it routes. Two properties
// make that safe — it takes no key (nothing to mishandle) and it hardcodes no
// origin (so the same folder is correct at /visible-reasoning/, at a root, and
// off file://).
ok(landing.includes('<h1>Bring your own key · the app gallery</h1>'), '[home] the header names the page');
ok(!landing.includes('type="password"') && !landing.includes('byok-key') && !landing.includes('byok-arm'),
  '[home] has NO key input — arming happens on the desk the visitor picked');
ok(!/sessionStorage|localStorage/.test(landing), '[home] touches no storage');
ok(landing.includes('data-testid="landing-custody"'), '[home] the custody explainer card is on the home');

// THE LANDING'S ONE SCRIPT. It used to carry none, and "no script" was the
// cheapest possible proof that it cannot misbehave. The about deck's flip needs
// aria-pressed and Enter/Space, which is a script — so the proof moves from
// "there is no code" to "here is all of the code, and here is what it cannot
// do". Everything below is asserted about the script's own bytes: exactly one,
// inline (nothing is fetched), and inside it no request, no storage, no key, no
// URL configuration. The custody claim is unchanged — the key path still has no
// server of ours in it, and this landing still takes no key at all.
const landingScripts = [...landing.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)];
ok(landingScripts.length === 1, '[home] carries exactly ONE script — the about-card flip, nothing else',
  `${landingScripts.length} script tag(s)`);
const landingJs = landingScripts.map((m) => m[2]).join('\n');
ok(landingScripts.every((m) => !/\bsrc=/.test(m[1])),
  '[home] that script is inline — the landing loads no code from anywhere');
ok(!/fetch\(|XMLHttpRequest|WebSocket|sendBeacon|new Image\(|import\(/.test(landingJs),
  '[home] the landing script makes no request of any kind');
ok(!/sessionStorage|localStorage|document\.cookie|indexedDB/.test(landingJs),
  '[home] the landing script touches no storage');
ok(!/apiKey|api\.anthropic|sk-ant|password/i.test(landingJs),
  '[home] the landing script knows nothing about keys');
ok(!/location|URLSearchParams|history\./.test(landingJs),
  '[home] the landing script reads no URL and navigates nowhere');
ok(landingJs.includes("deck.setAttribute('data-flip', 'on')") && landing.includes('data-about-deck'),
  '[home] the script only enhances its own deck — the about cards and nothing outside them');
// Scripting off must not hide anything: the deck is authored flat (both faces in
// flow) and the script is what stacks them, so a no-JS visitor still reads it.
ok(landing.includes('<div class="ab-deck" data-about-deck>') && !/<div class="ab-deck"[^>]*data-flip/.test(landing),
  '[home] the about deck ships flat — with scripting off every card back is still readable');

// The cards, and where they go.
for (const id of DESKS) {
  const app = APPS.find((a) => a.id === id);
  ok(landing.includes(`href="./${id}.html"`), `[home] the ${id} card links at ./${id}.html (relative)`);
  ok(landing.includes(`<h2 class="ag-title">${app.title}</h2>`), `[home] the ${id} card names the desk`);
  for (const s of app.starters) {
    ok(landing.includes(s.replace(/"/g, '&quot;')), `[home] the ${id} card shows the real starter “${s.slice(0, 34)}…”`);
  }
}
ok((landing.match(/Open the desk →/g) || []).length === DESKS.length,
  '[home] every runnable desk has a call to action', String((landing.match(/Open the desk →/g) || []).length));
for (const line of [
  `model: ${MODEL} — on your key, streamed token by token`,
  'browser-direct: every Claude call goes from your tab to api.anthropic.com — no server in between',
  'statuses and reply arrive as they happen',
  'every reply: visible reason → re-run without a source → fork',
]) ok(landing.includes(line), `[home] capability line: “${line.slice(0, 44)}…”`);

// The desk that cannot run in a browser: present, disabled, and it says why.
ok(landing.includes('class="ag-card off"'), '[home] the stock desk gets a card, disabled — not a deletion');
ok(!landing.includes('href="./stocks.html"') && !existsSync(join(outDir, 'stocks.html')),
  '[home] nothing links at a stock page, and none was generated');
ok(landing.includes('The SEC’s servers don’t allow browser calls, so the stock desk runs only in the server demo. Run it yourself with npm run gallery:live.'),
  '[home] the disabled card says why, and where the desk does run');
ok(landing.includes('Server-only — run it locally'), '[home] the disabled card’s CTA is honest about its state');

// The vocabulary, single-sourced from lib/page.js's table — and filtered to what
// THIS bundle can produce: nothing here is scripted, so that word never appears.
const guide = landing.slice(landing.indexOf('id="guide"'), landing.indexOf('</section>', landing.indexOf('id="guide"')));
ok(guide.includes('How to read the demo'), '[home] the guide section is on the home');
for (const state of ['live', 'fallback', 'synthetic', 'not consulted']) {
  const h = PROVENANCE_HELP.find((x) => x.state === state);
  ok(guide.includes(h.label) && guide.includes(h.what),
    `[home] #guide carries the “${h.label}” definition byte-equal from PROVENANCE_HELP`);
}
for (const cls of ['cd-dot live', 'cd-dot fallback', 'cd-dot synthetic', 'cd-dot notconsulted']) {
  ok(guide.includes(`class="${cls}"`), `[home] #guide paints a real “${cls}” dot (same classes as a desk)`);
}
// The body, not the stylesheet: the shared skin defines a paint for every
// verdict (it is one file), but nothing on this page may CLAIM one it cannot
// produce. Rendered content is where a claim lives.
const landingBody = landing.slice(landing.indexOf('<body>'));
ok(!landingBody.includes('scripted'),
  '[home] nothing rendered says “scripted” — no source in this bundle is');
ok(landing.includes('github.com/footprintjs/visible-reasoning'), '[home] the source link is on the page');

// The header rail and the about deck — both rendered from lib/page.js, so the
// two landings cannot drift. Asserted here because this is the PUBLIC page: a
// visitor who arrives cold gets the way to the code, to the library the desks
// run on, and to the five program notes.
for (const l of HEADER_LINKS) {
  ok(new RegExp(`<a href="${l.href.replace(/[/.]/g, '\\$&')}" target="_blank" rel="noopener"`).test(landing),
    `[home] the header rail links ${l.label} — new tab, rel=noopener`);
}
ok((landing.match(/data-testid="about-card"/g) || []).length === 5,
  '[home] the about deck has five cards', String((landing.match(/data-testid="about-card"/g) || []).length));
ok((landing.match(/role="button" tabindex="0" aria-pressed="false"/g) || []).length === 5,
  '[home] every about card ships un-flipped, keyboard-reachable, with aria-pressed on it',
  String((landing.match(/role="button" tabindex="0" aria-pressed="false"/g) || []).length));
ok(landing.includes('doi.org/10.1007/978-3-032-30849-8_1'),
  '[home] the about deck cites the paper by DOI');
for (const lib of ['footprintjs', 'agentfootprint', 'agentthinkingui']) {
  ok(landing.includes(`https://www.npmjs.com/package/${lib}`), `[home] the about deck links ${lib}`);
}
// The two build-specific facts: this bundle is two browser desks over keyless
// public APIs. A card that claimed three desks or a network it never touches
// would be exactly the dishonesty the rest of this file exists to prevent.
ok(landing.includes('Two desks run in your browser'), '[home] the about deck says TWO desks, not three');
ok(landing.includes('called straight from your tab'),
  '[home] the about deck describes browser-side tool calls, not a server’s');

// ═══ (f) same-tab navigation, without losing anything silently ══════════════
const LEAVE_CONFIRM = 'Leaving resets this conversation — your key stays per your “remember” choice.';
for (const d of deskPages) {
  const b = bootOf(d.html);
  ok(b.includes("href: './index.html'"), `[${d.id}] “← gallery” points at the bundle’s own home, relatively`);
  ok(b.includes("'data-testid': 'back-to-gallery'") && b.includes("'← gallery'"),
    `[${d.id}] the back link is labeled for what it is`);
  ok(!/href: '\.\/index\.html', onClick: onLeave,\s*\n?\s*'data-testid': 'back-to-gallery' \}[^)]*target/.test(b)
    && !b.includes("href: './index.html', target"),
    `[${d.id}] the gallery opens in the SAME tab`);
  ok(b.includes('onClick: onLeave'), `[${d.id}] leaving runs the guard`);
  ok(b.includes(LEAVE_CONFIRM), `[${d.id}] the guard's sentence names both costs — the conversation and the key`);
  ok(/function hasConversation\(\)/.test(b) && /if \(!hasConversation\(\)\) return;/.test(b),
    `[${d.id}] the guard fires only when there is a conversation to lose`);
  ok(b.includes('survives reload and the trip back to the gallery'),
    `[${d.id}] the key-travel promise is stated where the choice is made`);
}

// ═══ (g) no absolute paths anywhere — the subpath guarantee ═════════════════
// One escaped path is invisible at a domain root and a 404 under
// /visible-reasoning/, which is exactly where this bundle is published.
const ABSOLUTE = /(?:href|src)="\/(?!\/)/;
for (const page of [{ id: 'home', html: landing }, ...deskPages]) {
  ok(!ABSOLUTE.test(page.html), `[${page.id}] no absolute-path href/src — the page is subpath- and file://-safe`);
}
ok(Object.values(imports).every((t) => t.startsWith('./')),
  'every import-map target is relative', `${Object.keys(imports).length} specifiers`);

// ═══ the desk pages' badge, both modes (no live run needed) ═════════════════
const deskData = (model) => ({
  order: ['s1'], active: 's1', live: !!model, model, costNote: '',
  sessions: { s1: { id: 's1', label: trip.title, forkOf: null, appId: 'trip', ignoredSourceIds: [], seed: [], entity: 'Mission Peak', turns: [] } },
  reason: {}, rerun: {},
});
const mockDesk = buildAppPage(trip, deskData(null));
const liveDesk = buildAppPage(trip, deskData(MODEL));
ok(mockDesk.includes("'scripted mock — no model'"), 'mock desk page says “scripted mock — no model”');
ok(mockDesk.includes('"model":null'), 'mock desk page data carries model: null');
ok(liveDesk.includes(`"model":"${MODEL}"`), 'live desk page data carries the real model id');
ok(liveDesk.includes("'data-testid': 'model-badge'"), 'desk pages render the badge in both modes');

const mockGallery = buildGalleryPage(APPS, { live: false, model: MODEL });
const liveGallery = buildGalleryPage(APPS, { live: true, model: MODEL });
ok(mockGallery.includes('scripted mock — no model'), 'mock gallery cards say “scripted mock — no model”');
ok(liveGallery.includes(`model: ${MODEL}`), 'live gallery cards name the real model id');

// ═══ (e) the server has no routes ═══════════════════════════════════════════
const PORT = 4179;
const server = serve(PORT);
await new Promise((r) => server.once('listening', r));
try {
  const get = await fetch(`http://localhost:${PORT}/`);
  const post = await fetch(`http://localhost:${PORT}/`, { method: 'POST', body: '{}' });
  const postApi = await fetch(`http://localhost:${PORT}/app/trip/chat`, { method: 'POST', body: '{}' });
  ok(get.status === 200, 'the static server serves the page', `GET / → ${get.status}`);
  ok(post.status === 404, 'the static server refuses POST — it has no routes', `POST / → ${post.status}`);
  ok(postApi.status === 404, 'there is no chat endpoint to post a key to', `POST /app/trip/chat → ${postApi.status}`);
} finally {
  server.close();
}

console.log(failed === 0
  ? `\nAll checks passed — the BYOK artifact is structurally unable to record a key.`
  : `\n${failed} check(s) FAILED`);
process.exit(failed === 0 ? 0 : 1);
