// Static assertions over the generated BYOK artifact — seconds, no browser.
//
// The headless drive (chat → reason → re-run → fork, with a fake key, watching
// every network request) is the behavioural proof. THIS file is the one that
// runs on every change: it re-generates out/byok/ from scratch and then checks
// the properties that make the custody claim true as a matter of construction —
// the import map resolves, nothing key-shaped was written into the artifact, the
// page has no own-origin data path and no query-string configuration, and the
// model badge says the same honest thing in every mode.
//
//   node 08-app-gallery/verify-byok.mjs
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate, serve } from './byok.js';
import { buildAppPage, buildGalleryPage } from './lib/page.js';
import { trip } from './apps/trip.js';
import { APPS } from './apps/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'out', 'byok');
const MODEL = 'claude-haiku-4-5-20251001';

let failed = 0;
const ok = (cond, label, detail = '') => {
  if (!cond) failed += 1;
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${label}${detail ? ` — ${detail}` : ''}`);
};

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else if (entry.isFile()) yield p;
  }
}

// ═══ generate fresh ═════════════════════════════════════════════════════════
const { imports } = generate({ quiet: true });
const html = readFileSync(join(outDir, 'index.html'), 'utf8');
const boot = html.slice(html.lastIndexOf('<script type="module">'));
console.log('=== BYOK VERIFY ===');

// ═══ (a) the import map resolves ════════════════════════════════════════════
const unresolved = Object.entries(imports)
  .filter(([, target]) => !existsSync(join(outDir, target.replace(/^\.\//, ''))));
ok(unresolved.length === 0, 'every import-map entry points at a generated file',
  `${Object.keys(imports).length} specifiers`);
ok(['node:module', 'node:path', 'node:url'].every((k) => imports[k]?.startsWith('./app/byok/stubs/')),
  'node builtins are satisfied by in-page stubs, not left dangling');

// ═══ (b) nothing key-shaped, no server path, no env read ════════════════════
const REAL_KEY_SHAPE = /sk-ant-[A-Za-z0-9_-]{16,}/;
const offenders = [];
for (const file of walk(outDir)) {
  if (!['.html', '.js', '.json', '.css'].includes(extname(file))) continue;
  const body = readFileSync(file, 'utf8');
  if (REAL_KEY_SHAPE.test(body)) offenders.push(relative(outDir, file));
}
ok(offenders.length === 0, 'no key-shaped literal anywhere in the artifact', offenders.join(', ') || 'clean');

// The owner's own key must be provably absent — the generator never reads it,
// and this proves the artifact never carried it.
const envPath = join(here, '..', '.env');
if (existsSync(envPath)) {
  const ownerKey = (readFileSync(envPath, 'utf8').match(/ANTHROPIC_API_KEY\s*=\s*(\S+)/) ?? [])[1];
  if (ownerKey && ownerKey.length > 20) {
    let leaked = false;
    for (const file of walk(outDir)) {
      if (statSync(file).size > 20e6) continue;
      if (readFileSync(file, 'latin1').includes(ownerKey)) { leaked = true; break; }
    }
    ok(!leaked, "the owner's .env key does not appear anywhere in the artifact");
  } else {
    console.log('SKIP  owner-key check — no usable ANTHROPIC_API_KEY in .env');
  }
} else {
  console.log('SKIP  owner-key check — no .env present');
}

ok(!boot.includes('process.env'), 'the page script never reads an environment variable');
ok(!/fetch\(\s*['"`]\//.test(boot) && !boot.includes("'/app/"),
  'the page has no own-origin data path (no fetch to our server, no /app/ API prefix)');
ok(!/location\.search|URLSearchParams|hash\b/.test(boot),
  'no query-string / fragment configuration exists (a crafted link cannot redirect a key-bearing call)');
ok(boot.includes('__BYOK_TEST__') && boot.includes('apiUrlOverride'),
  'the only API-base override is the in-page test hook, read lazily at provider construction');
// The page is React-rendered from an empty <div id="root">, so the only way a
// form could exist is createElement('form') — assert it never happens.
ok(!boot.includes("e('form'") && !boot.includes("createElement('form'")
  && !/<body>[\s\S]*?<div id="root"><\/div>\s*<form/.test(html),
  'the key field is not inside a <form> — no submit default that could put it in a URL');

// ═══ (c) the right provider actually shipped ════════════════════════════════
const providerPath = join(outDir, 'vendor/agentfootprint/dist/esm/adapters/llm/BrowserAnthropicProvider.js');
const provider = existsSync(providerPath) ? readFileSync(providerPath, 'utf8') : '';
ok(provider.includes('anthropic-dangerous-direct-browser-access'),
  'the vendored browser provider carries the documented direct-browser header');
ok(provider.includes('https://api.anthropic.com/v1/messages'),
  'the provider’s API base is the compile-time Anthropic endpoint');
ok(/Browser providers do not read environment variables/.test(provider),
  'the browser provider takes its key ONLY from the caller');

// ═══ key custody, as written ════════════════════════════════════════════════
ok(boot.includes("sessionStorage.setItem"), 'a remembered key is written to sessionStorage');
ok(!boot.includes('localStorage.setItem'), 'nothing is ever written to localStorage');
ok(boot.includes("localStorage.removeItem"), '"Forget my key" clears localStorage too, unconditionally');
ok(/var apiKey = null/.test(boot), 'the key lives in a module-scoped page variable');
ok(boot.includes("keyTail = k.slice(-4)") || boot.includes('slice(-4)'),
  'only the last four characters are ever shown');

// ═══ (d) the custody copy + the three-state badge ═══════════════════════════
const mustSay = [
  'Your key stays in this tab.',
  'Every Claude call goes straight from your browser to',
  'our demo server never sees your key',
  'there is no server code that',
  'the only requests that carry your key go to',
  'Remember my key in this tab (survives reload; forgotten when the tab closes)',
  'Forget my key',
  'the SEC’s servers don’t allow browser calls, so the stock desk runs only in the server demo',
];
for (const phrase of mustSay) ok(html.includes(phrase), `custody copy present: “${phrase.slice(0, 52)}…”`);

ok(html.includes("'data-testid': 'model-badge'"), 'the BYOK page renders a model badge');
ok(html.includes('— direct from your browser · '), 'the badge says the call goes direct from the browser');
ok(html.includes("'no key yet'"), 'the badge has an honest no-key state');
ok(html.includes(MODEL), `the badge names the real model id (${MODEL})`);
ok(!html.includes('scripted mock'), 'the BYOK page never claims a mock — it is live-only by definition');

// ═══ the desk pages' badge, both modes (no live run needed) ═════════════════
const deskData = (model) => ({
  order: ['s1'], active: 's1', live: !!model, model, costNote: '',
  sessions: { s1: { id: 's1', label: trip.title, forkOf: null, appId: 'trip', ignoredSourceIds: [], seed: [], entity: 'Mission Peak', turns: [] } },
  reason: {}, rerun: {},
});
const mockDesk = buildAppPage(trip, deskData(null));
const liveDesk = buildAppPage(trip, deskData(MODEL));
ok(mockDesk.includes("'scripted mock — no model'"), 'mock desk page says “scripted mock — no model”');
ok(mockDesk.includes('"model":null'), 'mock desk page data carries model: null');
ok(liveDesk.includes(`"model":"${MODEL}"`), 'live desk page data carries the real model id');
ok(liveDesk.includes("'data-testid': 'model-badge'"), 'desk pages render the badge in both modes');

const mockGallery = buildGalleryPage(APPS, { live: false, model: MODEL });
const liveGallery = buildGalleryPage(APPS, { live: true, model: MODEL });
ok(mockGallery.includes('scripted mock — no model'), 'mock gallery cards say “scripted mock — no model”');
ok(liveGallery.includes(`model: ${MODEL}`), 'live gallery cards name the real model id');

// ═══ (e) the server has no routes ═══════════════════════════════════════════
const PORT = 4179;
const server = serve(PORT);
await new Promise((r) => server.once('listening', r));
try {
  const get = await fetch(`http://localhost:${PORT}/`);
  const post = await fetch(`http://localhost:${PORT}/`, { method: 'POST', body: '{}' });
  const postApi = await fetch(`http://localhost:${PORT}/app/trip/chat`, { method: 'POST', body: '{}' });
  ok(get.status === 200, 'the static server serves the page', `GET / → ${get.status}`);
  ok(post.status === 404, 'the static server refuses POST — it has no routes', `POST / → ${post.status}`);
  ok(postApi.status === 404, 'there is no chat endpoint to post a key to', `POST /app/trip/chat → ${postApi.status}`);
} finally {
  server.close();
}

console.log(failed === 0
  ? `\nAll checks passed — the BYOK artifact is structurally unable to record a key.`
  : `\n${failed} check(s) FAILED`);
process.exit(failed === 0 ? 0 : 1);
